//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_rb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public Flight()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
        public string Company { get; set; }
    
        public virtual Airport Arrival { get; set; }
        public virtual Airport Departure { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
