//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace db_rb.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.Passenger = new HashSet<Passenger>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual ICollection<Passenger> Passenger { get; set; }
    }
}
